# Generated by Django 6.0.3 on 2026-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trucks/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='chassis',
            field=models.CharField(max_length=17, unique=True, verbose_name='Chassi'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='color',
            field=models.CharField(choices=[('amarelo', 'Amarelo'), ('azul', 'Azul'), ('bege', 'Bege'), ('branca', 'Branca'), ('cinza', 'Cinza'), ('dourada', 'Dourada'), ('grena', 'Grená'), ('laranja', 'Laranja'), ('marrom', 'Marrom'), ('prata', 'Prata'), ('preta', 'Preta'), ('rosa', 'Rosa'), ('roxa', 'Roxa'), ('verde', 'Verde'), ('vermelha', 'Vermelha'), ('fantasia', 'Fantasia')], max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
