# Generated by Django 6.0.3 on 2026-06-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_truckbrand_alter_truck_model_truck_brand_truckmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trucks/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trucks.truck')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
