# Generated by Django 6.0.3 on 2026-06-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_seed_brands_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='trucks.truckmodel', verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
