# Generated by Django 6.0.3 on 2026-06-28 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_biometrictemplate_options_and_more'),
        ('trucks', '0006_alter_truck_truck_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truckphoto',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'Foto do Caminhão', 'verbose_name_plural': 'Fotos do Caminhão'},
        ),
        migrations.AlterField(
            model_name='truck',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca do caminhão (preenchida automaticamente pelo modelo).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='trucks.truckbrand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='chassis',
            field=models.CharField(help_text='Número do chassi com exatamente 17 caracteres alfanuméricos.', max_length=17, unique=True, verbose_name='Chassi'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='color',
            field=models.CharField(choices=[('amarelo', 'Amarelo'), ('azul', 'Azul'), ('bege', 'Bege'), ('branca', 'Branca'), ('cinza', 'Cinza'), ('dourada', 'Dourada'), ('grena', 'Grená'), ('laranja', 'Laranja'), ('marrom', 'Marrom'), ('prata', 'Prata'), ('preta', 'Preta'), ('rosa', 'Rosa'), ('roxa', 'Roxa'), ('verde', 'Verde'), ('vermelha', 'Vermelha'), ('fantasia', 'Fantasia')], help_text='Cor predominante do caminhão.', max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o caminhão está ativo para uso/associação.', verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(help_text='Placa do veículo no formato Mercosul (ABC1D23) ou antigo (ABC1234).', max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(default='', editable=False, help_text='Texto do modelo preenchido automaticamente (uso interno).', max_length=100, verbose_name='Modelo (texto)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto do caminhão.', null=True, upload_to='trucks/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_model',
            field=models.ForeignKey(help_text='Modelo do caminhão.', on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='trucks.truckmodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro.', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.IntegerField(blank=True, help_text='Ano de fabricação do caminhão (entre 1900 e o ano atual).', null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='truckassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora em que a associação foi criada.', verbose_name='Associado em'),
        ),
        migrations.AlterField(
            model_name='truckassignment',
            name='driver',
            field=models.ForeignKey(help_text='Funcionário motorista associado ao caminhão.', on_delete=django.db.models.deletion.PROTECT, related_name='truck_assignments', to='employees.employee', verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='truckassignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a associação.', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='truckassignment',
            name='truck',
            field=models.ForeignKey(help_text='Caminhão associado ao motorista.', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='trucks.truck', verbose_name='Caminhão'),
        ),
        migrations.AlterField(
            model_name='truckassignment',
            name='unassigned_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a associação foi encerrada (nulo = ativa).', null=True, verbose_name='Desassociado em'),
        ),
        migrations.AlterField(
            model_name='truckbrand',
            name='name',
            field=models.CharField(help_text='Nome da marca do caminhão (ex.: Volvo, Scania, Mercedes-Benz).', max_length=100, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='brand',
            field=models.ForeignKey(help_text='Marca à qual este modelo pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='trucks.truckbrand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='name',
            field=models.CharField(help_text='Nome do modelo do caminhão (ex.: FH 460, R 440, Actros).', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='truckphoto',
            name='image',
            field=models.ImageField(help_text='Arquivo de imagem do caminhão.', upload_to='trucks/photos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='truckphoto',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição da foto (menor = primeiro).', verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='truckphoto',
            name='truck',
            field=models.ForeignKey(help_text='Caminhão ao qual esta foto pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trucks.truck', verbose_name='Caminhão'),
        ),
        migrations.AlterField(
            model_name='truckphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora do upload da foto.', verbose_name='Enviado em'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['license_plate'], name='idx_truck_plate'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['chassis'], name='idx_truck_chassis'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['is_active'], name='idx_truck_active'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['brand', 'truck_model'], name='idx_truck_brand_model'),
        ),
        migrations.AddIndex(
            model_name='truckassignment',
            index=models.Index(fields=['truck', 'driver'], name='idx_assignment_truck_driver'),
        ),
        migrations.AddIndex(
            model_name='truckassignment',
            index=models.Index(fields=['assigned_at'], name='idx_assignment_assigned_at'),
        ),
        migrations.AddIndex(
            model_name='truckassignment',
            index=models.Index(fields=['unassigned_at'], name='idx_assignment_unassigned_at'),
        ),
        migrations.AddIndex(
            model_name='truckbrand',
            index=models.Index(fields=['name'], name='idx_truckbrand_name'),
        ),
        migrations.AddIndex(
            model_name='truckmodel',
            index=models.Index(fields=['brand', 'name'], name='idx_truckmodel_brand_name'),
        ),
        migrations.AddIndex(
            model_name='truckphoto',
            index=models.Index(fields=['truck', 'order'], name='idx_truckphoto_truck_order'),
        ),
    ]
