# Generated by Django 6.0.3 on 2026-07-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_alter_truckphoto_options_alter_truck_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o caminhão (opcional).', verbose_name='Observação'),
        ),
    ]
