# Generated by Django 6.0.7 on 2026-07-19 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_truck_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o caminhão (opcional).', validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='truckassignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a associação.', validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='truckbrand',
            name='name',
            field=models.CharField(help_text='Nome da marca do caminhão (ex.: Volvo, Scania, Mercedes-Benz).', max_length=100, unique=True, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='name',
            field=models.CharField(help_text='Nome do modelo do caminhão (ex.: FH 460, R 440, Actros).', max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Modelo'),
        ),
    ]
