# Generated by Django 6.0.3 on 2026-06-02 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.BinaryField()),
                ('finger_index', models.SmallIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Template Biométrico',
                'verbose_name_plural': 'Templates Biométricos',
            },
        ),
    ]
