# Generated by Django 6.0.3 on 2026-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document_photo',
            field=models.ImageField(blank=True, help_text='Imagem do documento de identificação do funcionário (RG, CNH, etc.).', null=True, upload_to='employees/documents/', verbose_name='Foto do Documento'),
        ),
    ]
