# Generated by Django 6.0.3 on 2026-06-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_document_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometrictemplate',
            options={'ordering': ['employee__name'], 'verbose_name': 'Template Biométrico', 'verbose_name_plural': 'Templates Biométricos'},
        ),
        migrations.AlterField(
            model_name='biometrictemplate',
            name='employee',
            field=models.OneToOneField(help_text='Funcionário associado a este template biométrico.', on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='employees.employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='biometrictemplate',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora do cadastro biométrico.', verbose_name='Cadastrado em'),
        ),
        migrations.AlterField(
            model_name='biometrictemplate',
            name='finger_index',
            field=models.SmallIntegerField(default=0, help_text='Índice do dedo utilizado na captura (0 = padrão).', verbose_name='Dedo'),
        ),
        migrations.AlterField(
            model_name='biometrictemplate',
            name='template',
            field=models.BinaryField(help_text='Dados binários do template biométrico (máx. 10 KB).', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='biometrictemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do template.', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, help_text='Departamento ao qual o funcionário está alocado.', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(help_text='Data em que o funcionário foi contratado.', verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o funcionário está ativo na empresa.', verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_driver',
            field=models.BooleanField(default=False, help_text='Indica se o funcionário está habilitado como motorista.', verbose_name='É Motorista?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Nome completo do funcionário.', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato.', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto de identificação do funcionário.', null=True, upload_to='employees/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(help_text='Cargo ou função do funcionário na empresa.', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro.', verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='biometrictemplate',
            index=models.Index(fields=['employee'], name='idx_biotemplate_employee'),
        ),
        migrations.AddIndex(
            model_name='biometrictemplate',
            index=models.Index(fields=['finger_index'], name='idx_biotemplate_finger'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='idx_employee_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='idx_employee_active'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='idx_employee_department'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_driver'], name='idx_employee_driver'),
        ),
    ]
