# Generated by Django 6.0.3 on 2026-07-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_move_biometrictemplate_to_biometric'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço completo do funcionário (opcional).', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP do endereço, no formato 00000-000 (opcional).', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do funcionário, no formato 000.000.000-00 (opcional).', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, help_text='Número do RG do funcionário (opcional).', max_length=20, verbose_name='RG'),
        ),
    ]
