# Generated by Django 6.0.3 on 2026-07-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_address_employee_cep_employee_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='foreign_document_number',
            field=models.CharField(blank=True, help_text='Número do documento de identificação apresentado pelo funcionário estrangeiro.', max_length=50, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='foreign_document_type',
            field=models.CharField(blank=True, help_text='Tipo do documento apresentado pelo funcionário estrangeiro (ex.: Passaporte, RNE).', max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_foreigner',
            field=models.BooleanField(default=False, help_text='Marque se o funcionário é estrangeiro e não possui RG/CPF.', verbose_name='Estrangeiro?'),
        ),
    ]
