# Generated by Django 6.0.7 on 2026-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_foreign_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='document_photo',
            field=models.FileField(blank=True, help_text='Imagem ou PDF do documento de identificação do funcionário (RG, CNH, etc.).', null=True, upload_to='employees/documents/', verbose_name='Foto do Documento'),
        ),
    ]
