# Generated by Django 6.0.7 on 2026-07-19 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_document_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço completo do funcionário (opcional).', max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP do endereço, no formato 00000-000 (opcional).', max_length=9, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do funcionário, no formato 000.000.000-00 (opcional).', max_length=14, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, help_text='Departamento ao qual o funcionário está alocado.', max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='foreign_document_number',
            field=models.CharField(blank=True, help_text='Número do documento de identificação apresentado pelo funcionário estrangeiro.', max_length=50, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='foreign_document_type',
            field=models.CharField(blank=True, help_text='Tipo do documento apresentado pelo funcionário estrangeiro (ex.: Passaporte, RNE).', max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Nome completo do funcionário.', max_length=200, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato.', max_length=20, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, help_text='Número do RG do funcionário (opcional).', max_length=20, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(help_text='Cargo ou função do funcionário na empresa.', max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Cargo'),
        ),
    ]
