# Generated by Django 6.0.3 on 2026-06-28 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_missing_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('page_view', 'Página Vista'), ('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('pdf', 'PDF Impresso'), ('login', 'Login'), ('logout', 'Logout')], help_text='Tipo de ação realizada (criação, atualização, exclusão, etc.).', max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='description',
            field=models.TextField(help_text='Descrição detalhada da ação realizada.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Endereço IP de onde a ação foi realizada.', null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='path',
            field=models.CharField(blank=True, help_text='URL ou caminho do sistema onde a ação foi executada.', max_length=500, verbose_name='Caminho'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a ação foi registrada.', verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário que realizou a ação (pode ser nulo se o usuário foi removido).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='username',
            field=models.CharField(help_text='Nome do usuário no momento da ação (preservado mesmo se o usuário for excluído).', max_length=150, verbose_name='Nome de Usuário'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('simple', 'Simples'), ('admin', 'Admin'), ('master', 'Master')], default='simple', help_text='Nível de acesso do usuário: Simples, Admin ou Master.', max_length=10, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Usuário do sistema associado a este perfil.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-timestamp'], name='idx_systemlog_timestamp'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', 'action'], name='idx_systemlog_user_action'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['action'], name='idx_systemlog_action'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='idx_userprofile_user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='idx_userprofile_role'),
        ),
    ]
