# Generated by Django 6.0.3 on 2026-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options_alter_systemlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('simple', 'Leitura'), ('admin', 'Admin'), ('master', 'Master')], default='simple', help_text='Nível de acesso do usuário: Leitura, Admin ou Master.', max_length=10, verbose_name='Função'),
        ),
    ]
