# Generated by Django 6.0.3 on 2026-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do usuário, somente números, validado automaticamente.', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indica se o usuário confirmou o email recebido no cadastro.', verbose_name='Email verificado'),
        ),
    ]
