# Generated by Django 6.0.7 on 2026-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_cpf_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização deste perfil (inclui alterações de role e do User relacionado, como ativar/desativar).', verbose_name='Atualizado em'),
        ),
    ]
