# Generated by Django 6.0.3 on 2026-06-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_employee_document_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('document_photo', models.ImageField(blank=True, help_text='Imagem do documento de identificação do visitante.', null=True, upload_to='visitors/documents/', verbose_name='Foto do Documento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Data da Visita')),
                ('arrival_time', models.TimeField(verbose_name='Hora de Chegada')),
                ('id_verified', models.BooleanField(default=False, help_text='A identificação com foto do visitante foi verificada?', verbose_name='Identificação com Foto Verificada')),
                ('scheduled_departure_time', models.TimeField(help_text='Horário previsto para o término da visita / expiração do crachá.', verbose_name='Hora de Partida (Prevista)')),
                ('actual_departure_time', models.TimeField(blank=True, help_text='Horário em que o visitante realmente deixou o local.', null=True, verbose_name='Hora Real da Partida')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_visits', to='employees.employee', verbose_name='Responsável pela Visita')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visitors.visitor', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-visit_date', '-arrival_time'],
            },
        ),
    ]
