# Generated by Django 6.0.3 on 2026-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto do rosto do visitante.', null=True, upload_to='visitors/photos/', verbose_name='Foto do Rosto'),
        ),
    ]
