# Generated by Django 6.0.3 on 2026-06-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_biometrictemplate_options_and_more'),
        ('visitors', '0002_visitor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='arrival_time',
            field=models.TimeField(help_text='Horário de chegada do visitante.', verbose_name='Hora de Chegada'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a visita.', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='responsible',
            field=models.ForeignKey(help_text='Funcionário responsável por receber o visitante.', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_visits', to='employees.employee', verbose_name='Responsável pela Visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro.', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(help_text='Data em que a visita ocorreu.', verbose_name='Data da Visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(help_text='Visitante que realizou a visita.', on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visitors.visitor', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(blank=True, help_text='Empresa à qual o visitante pertence (se aplicável).', max_length=200, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(help_text='Nome completo do visitante.', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato do visitante.', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro.', verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visitor', 'visit_date'], name='idx_visit_visitor_date'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['responsible'], name='idx_visit_responsible'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date'], name='idx_visit_date'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['name'], name='idx_visitor_name'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['company'], name='idx_visitor_company'),
        ),
    ]
