# Generated by Django 6.0.3 on 2026-07-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_visit_arrival_time_alter_visit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do visitante, no formato 000.000.000-00 (obrigatório, exceto para estrangeiros).', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='foreign_document_number',
            field=models.CharField(blank=True, help_text='Número do documento de identificação apresentado pelo visitante estrangeiro.', max_length=50, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='foreign_document_type',
            field=models.CharField(blank=True, help_text='Tipo do documento apresentado pelo visitante estrangeiro (ex.: Passaporte, RNE).', max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_foreigner',
            field=models.BooleanField(default=False, help_text='Marque se o visitante é estrangeiro e não possui RG/CPF.', verbose_name='Estrangeiro?'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rg',
            field=models.CharField(blank=True, help_text='Número do RG do visitante (obrigatório, exceto para estrangeiros).', max_length=20, verbose_name='RG'),
        ),
    ]
