# Generated by Django 6.0.7 on 2026-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_visitor_cpf_visitor_foreign_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='document_photo',
            field=models.FileField(blank=True, help_text='Imagem ou PDF do documento de identificação do visitante.', null=True, upload_to='visitors/documents/', verbose_name='Foto do Documento'),
        ),
    ]
