# Generated by Django 6.0.7 on 2026-07-19 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_alter_visitor_document_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(blank=True, help_text='Empresa à qual o visitante pertence (se aplicável).', max_length=200, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do visitante, no formato 000.000.000-00 (obrigatório, exceto para estrangeiros).', max_length=14, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='foreign_document_number',
            field=models.CharField(blank=True, help_text='Número do documento de identificação apresentado pelo visitante estrangeiro.', max_length=50, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='foreign_document_type',
            field=models.CharField(blank=True, help_text='Tipo do documento apresentado pelo visitante estrangeiro (ex.: Passaporte, RNE).', max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(help_text='Nome completo do visitante.', max_length=200, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato do visitante.', max_length=20, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='rg',
            field=models.CharField(blank=True, help_text='Número do RG do visitante (obrigatório, exceto para estrangeiros).', max_length=20, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='RG'),
        ),
    ]
