# Generated by Django 6.0.7 on 2026-07-19 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_visitor_company_alter_visitor_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a visita.', validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Observações'),
        ),
    ]
