# Generated by Django 6.0.3 on 2026-07-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identificação legível do quiosque (ex.: "Recepção - Matriz").', max_length=100, verbose_name='Nome')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash do Token')),
                ('token_prefix', models.CharField(editable=False, help_text='Primeiros caracteres do token, apenas para identificação em logs/admin.', max_length=8, verbose_name='Prefixo do Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
            ],
            options={
                'verbose_name': 'Dispositivo Quiosque',
                'verbose_name_plural': 'Dispositivos Quiosque',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['token_hash'], name='idx_kioskdevice_token_hash')],
            },
        ),
    ]
