# Generated by Django 6.0.3 on 2026-07-10 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0002_move_biometrictemplate_from_employees'),
        ('employees', '0008_employee_foreign_document_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricEnrollRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_requests', to='employees.employee', verbose_name='Funcionário')),
                ('fulfilled_by_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biometric.kioskdevice', verbose_name='Atendido pelo quiosque')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_enroll_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Cadastro Biométrico',
                'verbose_name_plural': 'Solicitações de Cadastro Biométrico',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='idx_enrollreq_status_reqat'), models.Index(fields=['employee', 'status'], name='idx_enrollreq_employee_status')],
            },
        ),
    ]
