# Generated by Django 6.0.7 on 2026-07-10 16:36

import employee_truck_control.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0003_biometricenrollrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometrictemplate',
            name='template',
            field=employee_truck_control.fields.EncryptedBinaryField(help_text='Dados binários do template biométrico (máx. 10 KB), criptografado em repouso.', verbose_name='Template'),
        ),
    ]
