# Generated by Django 6.0.7 on 2026-07-19 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0005_encrypt_existing_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskInstallerBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Versão do instalador (ex.: "1.1"), deve casar com MyAppVersion em kiosk_installer/installer.iss.', max_length=20, verbose_name='Versão')),
                ('file', models.FileField(help_text='O instalador ZK9500KioskSetup-*.exe gerado por kiosk_installer/build.ps1.', upload_to='kiosk_installer/', verbose_name='Arquivo')),
                ('notes', models.CharField(blank=True, help_text='Resumo opcional do que mudou nesta versão.', max_length=255, verbose_name='Notas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Instalador do Quiosque',
                'verbose_name_plural': 'Instaladores do Quiosque',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
