# Generated by Django 6.0.3 on 2026-06-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0003_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3)),
                ('timestamp', models.DateTimeField()),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presence_events', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_events', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Evento de Presença',
                'verbose_name_plural': 'Eventos de Presença',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='attendance__employe_2233a3_idx')],
            },
        ),
    ]
