# Generated by Django 6.0.3 on 2026-06-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_presenceevent'),
        ('employees', '0005_alter_biometrictemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='idx_attendance_emp_date',
            old_name='attendance__employe_b6a945_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='idx_attendance_emp_exit',
            old_name='attendance__employe_38a341_idx',
        ),
        migrations.RenameIndex(
            model_name='presenceevent',
            new_name='idx_presence_emp_ts',
            old_name='attendance__employe_2233a3_idx',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(help_text='Data do registro (preenchida automaticamente pela entrada).', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(help_text='Funcionário ao qual este registro de ponto pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='entry_time',
            field=models.DateTimeField(help_text='Data e hora da entrada do funcionário.', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='exit_time',
            field=models.DateTimeField(blank=True, help_text='Data e hora da saída do funcionário (nulo = ainda em aberto).', null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='presenceevent',
            name='attendance_record',
            field=models.ForeignKey(blank=True, help_text='Registro de ponto associado a este evento (se houver).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presence_events', to='attendance.attendancerecord', verbose_name='Registro de Ponto'),
        ),
        migrations.AlterField(
            model_name='presenceevent',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], help_text='Direção do evento: Entrada (IN) ou Saída (OUT).', max_length=3, verbose_name='Direção'),
        ),
        migrations.AlterField(
            model_name='presenceevent',
            name='employee',
            field=models.ForeignKey(help_text='Funcionário que gerou o evento biométrico.', on_delete=django.db.models.deletion.PROTECT, related_name='presence_events', to='employees.employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='presenceevent',
            name='timestamp',
            field=models.DateTimeField(help_text='Data e hora exata do evento biométrico.', verbose_name='Data/Hora'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='idx_attendance_date'),
        ),
        migrations.AddIndex(
            model_name='presenceevent',
            index=models.Index(fields=['direction'], name='idx_presence_direction'),
        ),
    ]
