# Generated by Django 6.0.7 on 2026-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_attendance__employe_b6a945_idx_idx_attendance_emp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização (ex.: quando a saída é registrada num registro em aberto).', verbose_name='Atualizado em'),
        ),
    ]
