# Generated by Django 6.0.7 on 2026-07-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='auto_closed',
            field=models.BooleanField(default=False, help_text='Marcado quando o funcionário esqueceu de bater a saída e o registro ficou aberto além do turno máximo permitido — deixa de contar como "em aberto" para a próxima batida (que passa a gerar uma nova entrada) e aparece na tela de revisão até que um administrador preencha a saída real.', verbose_name='Fechado automaticamente'),
        ),
    ]
