# Generated by Django 6.0.7 on 2026-07-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_auto_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_end',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o funcionário retornou do almoço.', null=True, verbose_name='Retorno do Almoço'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_start',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o funcionário saiu para o almoço.', null=True, verbose_name='Saída para Almoço'),
        ),
        migrations.AddField(
            model_name='presenceevent',
            name='is_lunch',
            field=models.BooleanField(default=False, help_text='Marca este evento como parte do intervalo de almoço — combinado com "direction", distingue Saída p/ Almoço (OUT) de Retorno do Almoço (IN), em vez da Entrada/Saída do dia.', verbose_name='É do Almoço?'),
        ),
    ]
